services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  local_rag_llm:
    build:
      dockerfile: Dockerfile-gpu
    image: local_rag_llm
    environment:
      HF_TOKEN: <your HF API token>
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    volumes:
      - <your_local_volume>:/app
      - <your_local_volume_with_models>:/app/models
    tty: true